# Generated by Django 3.1.3 on 2020-11-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregates", "0002_useraggregate"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="linkaggregate",
            index=models.Index(
                fields=["full_date"], name="aggregates__full_da_865352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="linkaggregate",
            index=models.Index(
                fields=["collection"], name="aggregates__collect_1c3986_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraggregate",
            index=models.Index(
                fields=["full_date"], name="aggregates__full_da_3a3ae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraggregate",
            index=models.Index(
                fields=["collection"], name="aggregates__collect_53b6a2_idx"
            ),
        ),
    ]
