# Generated by Django 3.1.3 on 2020-12-03 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20190730_1355'),
        ('aggregates', '0004_pageprojectaggregate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkaggregate',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
        migrations.AddIndex(
            model_name='linkaggregate',
            index=models.Index(fields=['organisation'], name='aggregates__organis_c142ff_idx'),
        ),
        migrations.AddIndex(
            model_name='pageprojectaggregate',
            index=models.Index(fields=['organisation'], name='aggregates__organis_dc6018_idx'),
        ),
        migrations.AddIndex(
            model_name='useraggregate',
            index=models.Index(fields=['organisation'], name='aggregates__organis_3955fd_idx'),
        ),
    ]
