# Generated by Django 3.1.4 on 2020-12-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregates", "0006_delete_aggregate_tables_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkaggregate",
            name="on_user_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pageprojectaggregate",
            name="on_user_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraggregate",
            name="on_user_list",
            field=models.BooleanField(default=False),
        ),
    ]
