# Generated by Django 4.2.19 on 2025-02-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0008_alter_linkaggregate_id_alter_pageprojectaggregate_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pageprojectaggregate',
            index=models.Index(fields=['full_date', 'collection_id', 'project_name', 'page_name'], name='aggregates__full_da_53fee7_idx'),
        ),
    ]
