# Generated by Django 4.2.19 on 2025-02-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0009_pageprojectaggregate_composite_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='linkaggregate',
            index=models.Index(fields=['organisation_id', 'collection_id', 'on_user_list', 'year', 'month'], name='aggregates__organis_286b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='pageprojectaggregate',
            index=models.Index(fields=['organisation_id', 'collection_id', 'project_name', 'page_name', 'on_user_list', 'year', 'month'], name='aggregates__organis_c106e7_idx'),
        ),
        migrations.AddIndex(
            model_name='useraggregate',
            index=models.Index(fields=['organisation_id', 'collection_id', 'username', 'on_user_list', 'year', 'month'], name='aggregates__organis_318980_idx'),
        ),
    ]
