# Generated by Django 4.2.19 on 2025-02-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0009_pageprojectaggregate_composite_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='linkaggregate',
            index=models.Index(fields=['organisation_id', 'collection_id', 'on_user_list'], name='aggregates__organis_f609df_idx'),
        ),
        migrations.AddIndex(
            model_name='pageprojectaggregate',
            index=models.Index(fields=['organisation_id', 'collection_id', 'project_name', 'page_name', 'on_user_list'], name='aggregates__organis_b25ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='useraggregate',
            index=models.Index(fields=['organisation_id', 'collection_id', 'username', 'on_user_list'], name='aggregates__organis_f7a403_idx'),
        ),
    ]
