# Generated by Django 4.2.19 on 2025-03-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregates", "0010_add_aggregate_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pageprojectaggregate",
            index=models.Index(
                fields=["organisation", "project_name"],
                name="aggregates__organis_572036_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useraggregate",
            index=models.Index(
                fields=["organisation", "username"],
                name="aggregates__organis_05ef9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageprojectaggregate",
            index=models.Index(
                fields=["collection", "project_name", "page_name"],
                name="aggregates__collect_e1e227_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useraggregate",
            index=models.Index(
                fields=["collection", "username"], name="aggregates__collect_463085_idx"
            ),
        ),
    ]
