# Dockerfile
FROM python:3.5.2

ENV LOG_FILE="eventstream.log"

WORKDIR /app
COPY . extlinks
COPY requirements/django.txt /app/

RUN mkdir logs

RUN pip install -r django.txt

CMD ["python", "manage.py", "linkevents_collect", "--historical"]
