# Generated by Django 3.1.1 on 2020-10-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20201002_0244'),
        ('programs', '0002_auto_20190603_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='organisations', to='organisations.Organisation'),
        ),
    ]
