# Generated by Django 3.1.1 on 2020-10-02 02:44

from django.db import migrations, models


def add_orgs_to_program(apps, schema_editor):
    Organisation = apps.get_model("organisations", "Organisation")
    Program = apps.get_model("programs", "Program")

    programs = Program.objects.all()

    for program in programs:
        related_orgs = Organisation.objects.filter(program=program)

        # If program.organisations has no information and related_orgs returns
        # organisations, the related_orgs will be added to the program
        if program.organisations.count() == 0 and related_orgs.count() > 0:
            program.organisations.add(related_orgs)
            program.save()


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_program_organisations"),
    ]

    operations = [migrations.RunPython(add_orgs_to_program)]
