# Generated by Django 2.2 on 2019-04-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=60)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='LinkSearchTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.PositiveIntegerField()),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.URLPattern')),
            ],
        ),
        migrations.CreateModel(
            name='LinkEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2083)),
                ('timestamp', models.DateTimeField()),
                ('domain', models.CharField(max_length=32)),
                ('rev_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('page_title', models.CharField(max_length=255)),
                ('page_namespace', models.IntegerField()),
                ('change', models.IntegerField(choices=[(0, 'Removed'), (1, 'Added')])),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.URLPattern')),
            ],
        ),
    ]
