# Generated by Django 2.2 on 2019-04-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linksearchtotal',
            options={'verbose_name': 'LinkSearch total', 'verbose_name_plural': 'LinkSearch totals'},
        ),
        migrations.AlterModelOptions(
            name='urlpattern',
            options={'verbose_name': 'URL pattern', 'verbose_name_plural': 'URL patterns'},
        ),
    ]
