# Generated by Django 2.2 on 2019-05-20 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksearchtotal",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
