# Generated by Django 2.2 on 2019-04-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190415_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkevent',
            name='on_user_list',
            field=models.BooleanField(default=False),
        ),
    ]
