# Generated by Django 2.2 on 2019-05-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190520_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpattern',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
