# Generated by Django 2.2 on 2019-04-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_linkevent_on_user_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkevent',
            name='event_id',
            field=models.CharField(default=11, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkevent',
            name='rev_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='linkevent',
            name='url',
        ),
        migrations.AddField(
            model_name='linkevent',
            name='url',
            field=models.ManyToManyField(related_name='linkevent', to='links.URLPattern'),
        ),
        migrations.AlterField(
            model_name='urlpattern',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url', to='programs.Collection'),
        ),
    ]
