# Generated by Django 3.1.14 on 2023-02-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_fill_proquest_openurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkevent',
            name='hash_link_event_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddIndex(
            model_name='linkevent',
            index=models.Index(fields=['hash_link_event_id'], name='links_linke_hash_li_594ad2_idx'),
        ),
    ]
