# Generated by Django 3.1.14 on 2023-02-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_data_link_event_id_hash'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='linkevent',
            index=models.Index(fields=['timestamp'], name='links_linke_timesta_4a56de_idx'),
        ),
    ]
