# Generated by Django 4.2.14 on 2024-08-08 17:48

from django.db import migrations, models
import extlinks.links.models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_alter_linkevent_id_alter_linksearchtotal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkevent',
            name='url_patterns',
            field=models.JSONField(default=extlinks.links.models.LinkEvent.url_patterns_default),
        ),
    ]
