# Generated by Django 4.2.14 on 2024-08-08 17:59

from django.db import migrations


def copy_urls(apps, schema_editor):
    LinkEvent = apps.get_model("links", "LinkEvent")
    for link_event in LinkEvent.objects.all():
        link_event.url_patterns = {"id": link_event.url.values_list("id", flat=True)}


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_linkevent_url_patterns'),
    ]

    operations = [
        migrations.RunPython(copy_urls),
    ]
