# Generated by Django 4.2.14 on 2024-08-08 17:59

from django.core.paginator import Paginator
from django.db import migrations


def copy_urls(apps, schema_editor):
    # same chunk size as linkevents_archive command
    chunk = 100000
    LinkEvent = apps.get_model("links", "LinkEvent")
    paginator = Paginator(
        LinkEvent.objects.filter(url_patterns__id="[]").order_by("id"), chunk
    )
    for page_num in paginator.page_range:
        link_events = paginator.page(page_num).object_list
        for link_event in link_events:
            url_ids = list(link_event.url.values_list("id", flat=True))
            link_event.url_patterns = {"id": url_ids}
            link_event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0013_linkevent_url_patterns"),
    ]

    operations = [
        migrations.RunPython(copy_urls),
    ]
