# Generated by Django 4.2.14 on 2024-09-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('links', '0014_migrate_url_pattern_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkevent',
            name='url',
        ),
        migrations.RemoveField(
            model_name='linkevent',
            name='urlpattern',
        ),
        migrations.AddField(
            model_name='linkevent',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='linkevent',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='linkevent',
            index=models.Index(fields=['content_type', 'object_id'], name='links_linke_content_1a162a_idx'),
        ),
    ]
