# Generated by Django 4.2.14 on 2024-09-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0014_migrate_url_pattern_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkevent',
            name='url',
        ),
    ]
