# Generated by Django 3.1.1 on 2020-10-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20190603_1255'),
        ('organisations', '0006_auto_20190730_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='program', to='programs.Program'),
        ),
    ]
